In [1]:
# NumPy->"Numerical Python"....Py lib...used for working with arrays.
# It also has functions for working in domain of linear algebra, fourier transform, and matrices.

# alias: In Python alias are an alternate name for referring to the same thing.
# Create an alias with the "as" keyword while importing....numpy alias is..np

import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [2]:
# Why Use NumPy?
# NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
#       NumPy arrays are stored at one continuous place in memory unlike lists, 
#       so processes can access and manipulate them very efficiently.
# array object in NumPy is called ndarray
# used -> data science, where speed and resources are very important.

# Which Language is NumPy written in?
# NumPy is a Python library and is written partially in Python,
# but most of the parts that require fast computation are written in C or C++.

import numpy
arr=numpy.array(["waj","eeha","eiman"])
print(arr)

['waj' 'eeha' 'eiman']


In [3]:
# Checking NumPy Version
import numpy as np
print(np.__version__)

1.24.3


In [4]:
# Create a NumPy ndarray Object.. create a NumPy ndarray object by using the array() function.
arr=np.array([1,2,3,4,5])
print(arr)
# type() ->built-in Python function tells us the type of the object passed to it.
# yahan ...arr is numpy.ndarray type.
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# To create an ndarray..can pass a list, tuple or any array-like object into the array() method
#  and it will be converted into an ndarray

# Use a tuple to create a NumPy array
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [6]:
# dimension in arrays....one level of array depth (nested arrays).
# nested array: are arrays that have arrays as their elements

# 0-D arrays, or Scalars....are the elements in an array. Each value in an array is a 0-D array.
# Create a 0-D array with value 42
arr=np.array(42)
print(arr)

42


In [7]:
#array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.... most comman typr of array
# Create a 1-D array containing the values 1,2,3,4,5:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [8]:
# NumPy has a whole sub module dedicated towards matrix operations called numpy.mat

# An array that has 1-D arrays as its elements is called a 2-D array.
# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [9]:
# An array that has 2-D arrays (matrices) as its elements is called 3-D array
# Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [10]:
# Check Number of Dimensions
# ndim attribute....returns an integer ....how many dimensions the array have

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [11]:
# Higher Dimensional Arrays....can have any number of dimensions
# Create an array with 5 dimensions
# using the ndmin argument....define the number of dimensions
arr=np.array([1,2,3],ndmin=5)
print(arr.ndim)

5


In [12]:
# In this array the innermost dimension (5th dim) has 4 elements, 
# the 4th dim has 1 element that is the vector, 
# the 3rd dim has 1 element that is the matrix with the vector,
# the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.

In [13]:
# Array indexing....accessing an array element....by referring to its index number.... index starting with 0 and so on...
arr=np.array((1,2,3,4,5,6))#tuple
print(arr[0])#first element
print(arr[3],arr[4])#3rd and 4th element

1
4 5


In [14]:
# 2-D arrays.... like a table with rows and columns, where the dimension represents the row and the index represents the column.
arr=np.array([[1,2,3],
              [4,5,6]])
print(arr[1][0])# Access the element on the first row, second column
# or
print(arr[1,2])# Access the element on the first row, 3rd column

4
6


In [15]:
# 3-D arrays

# Access the third element of the second array of the first array
arr=np.array([[[1,2,3,4],
               [5,6,7,8]],
              
            [[1,2,3,4],
             [5,6,7,8]]])
print(arr)
print(arr[0][1][2])

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]
7


In [16]:
# Use negative indexing.... to access an array from the end.
# Print the last element from the 2nd dim
arr=np.array([[1,2,3,4,],[5,6,7,8]])
print(arr[1][-1] )

# arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
# print('Last element from 2nd dim: ', arr[1, -1])


8


In [17]:
# Slicing arrays....taking elements from one given index to another given index.
# [start:end]. or  [start:end:step]

# Slice elements from index 1 to index 5
arr=np.array([1,2,3,4,5,6,7,8])
print("a .",arr[2:5])
print("b .",arr[4:])#from index 4 to the end of the array
print("c .",arr[:4])# from the beginning to index 4 

# Negative Slicing
print("d .",arr[-3:-1])#from the index 3 from the end to index 1 from the end

#STEP
print("e .",arr[1:5:2]) #Return every other element from index 1 to index 5
print("f .",arr[::2])#Return every other element from the entire array

a . [3 4 5]
b . [5 6 7 8]
c . [1 2 3 4]
d . [6 7]
e . [2 4]
f . [1 3 5 7]


In [18]:
#Slicing 2-D Arrays
arr=np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])
print(arr,"\n")
# From the second element, slice elements from index 1 to index 4 
print("a .",arr[1,1:4])
# Note: Remember that second element has index 1.

# From both elements, return index 2:
print("b .",arr[0:2,2])

# From both elements, slice index 1 to index 4 
print("c .",arr[0:2,1:4])

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]] 

a . [10 11 12]
b . [ 3 11]
c . [[ 2  3  4]
 [10 11 12]]


In [19]:
# # NumPy Data Types
# strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
# integer - used to represent integer numbers. e.g. -1, -2, -3
# float - used to represent real numbers. e.g. 1.2, 42.42
# boolean - used to represent True or False.
# complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

# check data type 
arr=np.array([1,5])
print(arr.dtype)
arr1=np.array([1j,5j])
print(arr1.dtype)


# Creating Arrays With a Defined Data Type
# Create an array with data type string
arr2 = np.array([1, 2, 3, 4], dtype='S')
print(arr2)
print(arr2.dtype)

# Create an array with data type 4 bytes integer
arr3=np.array([1,2,3,4],dtype="i4")
print(arr3)
print(arr3.dtype)


# A non integer string like 'a' can not be converted to integer 
# arr4=np.array(['a','4','3'],dtype="i")# it create error

int32
complex128
[b'1' b'2' b'3' b'4']
|S1
[1 2 3 4]
int32


In [28]:
# astype() method....function creates a copy of the array, and allows you to specify the data type as a parameter.

# Change data type from float to integer by using 'i' as parameter value
arr=np.array([2.3,4.6,3.2])
narr=arr.astype('i')#or narr=arr.astpye(int) 
print(narr)
narr2=arr.astype(bool)#data type from integer to boolean
print(narr2)
print(narr2.dtype)

[2 4 3]
[ True  True  True]
bool


In [34]:
# Difference Between Copy and View
# copy :
# is a new array
# owns the data and
# any changes made to the copy will not affect original array and
# any changes made to the original array will not affect the copy
# view :
# is just a view of the original array.
# does not own the data and 
# any changes made to the view will affect the original array, and 
# any changes made to the original array will affect the view

arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x,"\n")#no chnages made when there is change in original array

y=arr.view()
arr[1]=456
print(arr)
print(y)#chnage is made when there is change in original array


# Check if Array Owns its Data
# base  attribute refers to the original object.....returns None if the array owns the data
print(x.base)#returned none
print(y.base)#returned original array

[42  2  3  4  5]
[1 2 3 4 5] 

[ 42 456   3   4   5]
[ 42 456   3   4   5]
None
[ 42 456   3   4   5]


In [50]:
# array shape=number of elements in each dimension.
# attribute shape .....returns a tuple with each index having the number of corresponding elements.
arr=np.array([[1,2,3],[2,4,6]])
print(arr.shape)#array has 2 dimensions, where the first dimension has 2 elements and the second has 4.
arr=np.array([1,2,3])
print(arr.shape)#1 dim , and have 3 elements

arr=np.array([[[1,2,3],[1,2,3]],
             [[2,4,6],[1,2,3]]])
print(arr)
print(arr.shape)

(2, 3)
(3,)
[[[1 2 3]
  [1 2 3]]

 [[2 4 6]
  [1 2 3]]]
(2, 2, 3)


In [48]:
#Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4
arr=np.array([1,2,3,4], ndmin=5)
print(arr)
print(arr.shape)
arr.ndim

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


5

In [59]:
# Reshaping arrays....changing the shape of an array.
# we can add or remove dimensions or change number of elements in each dimension.
#1-D TO 3-D
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
narr=arr.reshape(3,4)
print(arr)
print(narr)
print(arr.shape)
print(narr.shape)

#can not reshape any number of elemet into tha shape..array of 8 elment can be change to (2,4)or(4,2)..but not to (3,3)...3*3=9
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# newarr = arr.reshape(3, 3)#error
newarr=arr.reshape(2,4)
print(newarr)
print(newarr.base)#it is a view not a copy,returns original array

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(12,)
(3, 4)
[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [61]:
# allowed to have one "unknown" dimension...you do not have to specify an exact number for one of the dimensions in the reshape method.
arr=np.array([1,2,3,4,5,6,7,8])
newarr=arr.reshape(2,2,-1)
print(newarr)
#  We can not pass -1 to more than one dimension.

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [64]:
# Flattening array...converting a multidimensional array into a 1D array.
# use reshape(-1) to do this.
arr=np.array([[1, 2, 3],
              [4, 5, 6]])
print(arr)
new=arr.reshape(-1)
print(new)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [80]:
# Iterating Arrays... going through elements one by one....do this using basic for loop
arr=np.array([1,2,3,4,5,6])
for x in arr:
    print(x)
    
    
# 2-D array... go through reading the rows.
# n-D array it will go through n-1th dimension one by one
arr=np.array([[1,2,3],
              [4,5,6]])
for x in arr:
    print(x)
# for iterating each scaler element:
for x in arr:
    for y in x:
        print(y)
    
print("\n\n")    
arr=np.array([[[1,2,3],[1,2,3]],
             [[2,4,6],[1,2,3]]])# iterate 3-D Arrays
for x in arr:
    print("rows")
    print(x)
    
# # for iterating each scaler element:
for x in arr:
#     print("w")
    for y in x:
#         print("w")
        for z in y:
#             print("r")
            print(z)

1
2
3
4
5
6
[1 2 3]
[4 5 6]
1
2
3
4
5
6



rows
[[1 2 3]
 [1 2 3]]
rows
[[2 4 6]
 [1 2 3]]
w
1
2
3
1
2
3
w
2
4
6
1
2
3


In [81]:
# Iterating Arrays Using nditer()
arr = np.array([[[1, 2], [3, 4]], 
                [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [89]:
# op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.
arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

#  needs some other space to perform this action, that extra space is called buffer

b'1'
b'2'
b'3'


In [90]:
# Iterating With Different Step Size
# Iterate through every scalar element of the 2D array skipping 1 element
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [ ]:
# Enumerated Iteration Using ndenumerate()
# Enumeration .... mentioning sequence number of somethings one by one.